### ISSUE TITLE
Adding "Find All References" functionality

### ISSUE THREAD

**Issue by Vatyx** [Hazelight/vscode-unreal-angelscript#20]
Hello!

"Find All References" is something I frequently use in most editors and was very sad to see that this plugin doesn't have it, so I was thinking I could help out with implementing it. I had a look through the Language Server code, mainly `as_file.ts` and `database.ts` and it doesn't seem like the current structure suits well to querying for all references of a symbol, however if I'm mistaken please let me know.

My idea was build up a data structure, similar to `export let database = new Map<string, DBType>();` which can specifically be queried for finding references to a symbol. The data structure would be modified on document modification and would contain info on both usages of types and variables. Potentially the complexity for local variables could be minimized here and enough context already exists inside an `AScope`, but I'm not sure how to implement "find all references" for member variables without some kind of structure to query. What are your thoughts?

**Comment by GGLucas** [comment]
Sounds like a cool project!

You would definitely need a new data structure for this, both for local and member variables.
The existing type database only searches for variable _declarations_, and completely ignores variable _usages_ (and it uses ugly regex hacks for it to boot), so you would need to implement your own parsing for these from scratch.

I don't think you'd be able to get around creating a full grammar-based parser for angelscript code to be able to implement this, since you need to be able to parse expressions and use context information to infer which property is being used.

**Comment by Vatyx** [comment]
Hmm, this parser must exist in the compiler? Potentially that can be pulled out? Granted I have no idea how reusable the parser is and what it would look like

**Comment by GGLucas** [comment]
Implemented in v1.0.0 of the extension.
