### ISSUE TITLE
problems with `>>`; e.g., `cast<TArray<T>>`, or `auto x = 2 >> 1` being detected as bool

### ISSUE THREAD

**Issue by XertroV** [Hazelight/vscode-unreal-angelscript#34]
I found this while developing the openplanet fork. I'm making an issue instead of a PR b/c you might prefer your own implementation. Here is my fix: https://github.com/XertroV/vscode-openplanet-angelscript/commit/38cc55d1b727bdd065507e8c7b7a2758d5aa98cd#diff-4910283f7c594d7e0b62d17c3cc269acdb6182b6e865c129cc4e3ea2297f5820

The problem is mostly caused by 2 things at the same time: operator precedence and the lexer.

1. the lexer splits up the doc in advance, so if something is matched by the lexer, it's treated as a single chunk.
2. the only precedence that I found which worked is `>>>` over `>>` over `>`. a single rule like `op_binary_shift -> ("<" "<" | ">" ">" | ">" ">" ">")` did not work (only `<<` and `>>` would be matched, never `>>>`). in part this was b/c it preferred `(>>)(>)` over `>>>`.

old behavior wrt operator precedence: `a >> b` would be parsed as `((a >) > b)` due to the way the RHS of the expression is optional + the ability to match 2 `>` or `>>` in the same rule.

this meant that `auto x = 2 >> 1` would be parsed as `auto x = (2 >) > 1` which was (incorrectly) detected as a bool.

additionally, it meant that matching template types (or casts) of the form `cast<TOuter<T>>` or `TOuter<TInner<T>>` would fail b/c `>>` was detected as an operator and did not match individual `>` symbols.

solution:

1. exclude `>>` and `<<` from the lexer. instead, detect them in the parser with rules that match `">" ">" | "<" "<"`
2. ensure that no rules can match both `>>` and `>>>` (etc) at the same precedence
3. longer operators need to take precedence

types are now correctly detected and nested template types are correctly parsed:

![image](https://user-images.githubusercontent.com/1046448/196635599-d2b13ac1-168a-498a-95f9-5ec7e0a8cd9e.png)

![image](https://user-images.githubusercontent.com/1046448/196635208-d4811e37-1583-460f-af1f-877dfe88d32d.png)

**Comment by GGLucas** [comment]
Haha, this is another case where I took shortcuts because of unreal limitations actually.
Unreal doesn't allow directly nested containers at all, so you can never actually get templates deeper than `>>` in UE-AS scripts.
You can see I also cheated some of the parsing ambiguity by hardcoding the available container types, since at least in our plugin there's a pretty small number of allowable containers that unreal understands.

The bug with parsing `2 >> 1` is concerning though. (Although I can probably count the amount of times we've actually used bit shifts in our game scripts on one hand haha)
I definitely will take a look at your solution, thank you for sharing it!
Although changing the operator parsing _is_ a bit scary. In the past it has been by far the most combinatorially complex part of the rules and makes it really easy to wreck the parsing performance.

**Comment by XertroV** [comment]
> You can see I also cheated some of the parsing ambiguity by hardcoding the available container types, since at least in our plugin there's a pretty small number of allowable containers that unreal understands.

Yeah, I piggybacked on that b/c it's a similar situation with openplanet's flavor. Users can't create new template types, so there's only half a dozen or so to account for.

> (Although I can probably count the amount of times we've actually used bit shifts in our game scripts on one hand haha)

Yeah, I figured it wasn't that big a deal since it's a pretty uncommon operation and it doesn't break anything besides the LS type resolution afaik (which has very little impact).

> Although changing the operator parsing is a bit scary. In the past it has been by far the most combinatorially complex part of the rules and makes it really easy to wreck the parsing performance.

Good to know it's a bottleneck for parsing performance. I didn't run into that with my testing last night, but I'll keep it in mind.

That reminds me of a pegged 100% CPU bug with my fork (not sure exactly what was looping infinitely but something was) -- after some profiling and a binary search of what code was responsible, this was the solution: 
![image](https://user-images.githubusercontent.com/1046448/196821719-3e578c72-f1ff-4274-a280-e4ebd9ac7323.png)

So yeah, potentially big impacts from small changes. 

An alternate solution I thought of was reprocessing the AST output to detect the case of `BinaryOp<BinaryOp<left,null>,right>` (where `.operator == ">"` for both) and replacing it with the corrected expression. If you are interested in fixing the type resolution without touching the parser, that might be a less risky method (although a bit hack-y).

**Comment by GGLucas** [comment]
I tested it out over here, and it looks like `2 >> 1` is being correctly detected as `int` for me.
Most likely because the lexer is disambiguating it by parsing `>>` as one token, which I think you've removed in your fork.

Since the template and cast parsing issues are not possible to trigger for us due to unreal limitations, I'm going to close this issue.
But thank you for taking the time to report it and providing your analysis!

**Comment by XertroV** [comment]
> Most likely because the lexer is disambiguating it by parsing `>>` as one token, which I think you've removed in your fork.

I have now - but that's pretty recent. I don't know if it was being incorrectly detected before I started fiddling with `>>` yesterday.
I changed some things earlier when I was trying to get template types working (like a week or more ago), so I might have broken the type detection then without knowing, too (since opShr is pretty rare).

In any case, glad to hear it's not an issue.

> I'm going to close this issue.

👍 sounds good.
