### ISSUE TITLE
file decorations on parse errors and squiggles

### ISSUE THREAD

**Issue by XertroV** [Hazelight/vscode-unreal-angelscript#35]
Some code I wrote to add file decorations to show parse errors ("4 E" on RHS of file name + all in red), and also some code to add squiggles to parse errors. You're welcome to copy paste any of it if you'd like those features for this plugin.

File decorations: https://github.com/XertroV/vscode-openplanet-angelscript/commit/f1d4024a0bcb11748bea12ed35f292072e7a2cc8

Squiggle (v easy to implement): https://github.com/XertroV/vscode-openplanet-angelscript/blob/f1d4024a0bcb11748bea12ed35f292072e7a2cc8/language-server/src/ls_diagnostics.ts#L118-L133

edit: screenshot might help. (please excuse the not-markdown in the hover box thing)
![image](https://user-images.githubusercontent.com/1046448/196873031-5b8adb8c-178c-453c-88bc-827a5cf338a6.png)

**Comment by GGLucas** [comment]
Thanks for the suggestion!

I think I will pass on this one though, because it can still be fairly easy to cause parse errors by just being in the middle of typing a line, and you don't really want squigglies appearing while you're still typing something. (You potentially could mitigate this by checking whether the statement is currently being typed on)

I'm not sure how it is for your integration, but the unreal plugin will immediately detect when you save a file and compile and send through diagnostics. So we have a more "press save to see errors" workflow that this wouldn't add much to, since the angelscript compiler will give much clearer error messages anyway.
